import Head from 'next/head'
import { Container,Snackbar,Alert } from '@mui/material'
import TodoList from '@/components/TodoList'
import TodoForm from '@/components/TodoForm'
import { TodoContext } from '@/contexts/TodoContext'
import { useState } from 'react'
import Loading from '@/components/Loading'

export default function Home() {
  const [open,setOpen]=useState(false);
  const [alertType,setAlertType]=useState("success");
  const [alertMessage,setAlertMessage]=useState("");
  const [todo,setTodo]=useState({
    baslik:"",
    aciklama:""
  })

  const showAlert=(type,msg)=>{
    setAlertMessage(msg);
    setAlertType(type);
    setOpen(true);
  }

  const handleClose = (event,reason) => {
    if (reason === 'clickaway') {
      return;
    }

    setOpen(false);
  };
  
  return <Loading type="spinningBubbles" color="grey"/>
  return (
    <TodoContext.Provider value={{showAlert,todo,setTodo}}>
        <Container maxWidth="md">
        <Head>
          <title>SC Todo App</title>
          <meta name="description" content="This app generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <TodoForm/>
        <Snackbar anchorOrigin={{vertical:"top",horizontal:"center"}} open={open}
        autoHideDuration={4000} onClose={handleClose}>
          <Alert onClose={handleClose} severity={alertType} sx={{width:"100%"}}>
            {alertMessage}
          </Alert>
        </Snackbar>
        <TodoList/>
      </Container>
    </TodoContext.Provider>
  )
}
